// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT19eA_cla8z_j9uHv5u7eWwJUS_JMVSc',
    appId: '1:532773088511:web:a55e52132dd0dbd86670ca',
    messagingSenderId: '532773088511',
    projectId: 'kisisel-asistan-381e6',
    authDomain: 'kisisel-asistan-381e6.firebaseapp.com',
    storageBucket: 'kisisel-asistan-381e6.firebasestorage.app',
    measurementId: 'G-KHM7LQFX1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCvqLCEFC-V0A7XJcfxVOqURNnZWMVD8',
    appId: '1:532773088511:android:f8d7e7f90d6cf0316670ca',
    messagingSenderId: '532773088511',
    projectId: 'kisisel-asistan-381e6',
    storageBucket: 'kisisel-asistan-381e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZn8qfpSqG2u9J1sgn9f3bShsvjokg_c',
    appId: '1:532773088511:ios:17db38ef061941476670ca',
    messagingSenderId: '532773088511',
    projectId: 'kisisel-asistan-381e6',
    storageBucket: 'kisisel-asistan-381e6.firebasestorage.app',
    iosBundleId: 'com.example.kisiselAsistanFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSZn8qfpSqG2u9J1sgn9f3bShsvjokg_c',
    appId: '1:532773088511:ios:17db38ef061941476670ca',
    messagingSenderId: '532773088511',
    projectId: 'kisisel-asistan-381e6',
    storageBucket: 'kisisel-asistan-381e6.firebasestorage.app',
    iosBundleId: 'com.example.kisiselAsistanFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT19eA_cla8z_j9uHv5u7eWwJUS_JMVSc',
    appId: '1:532773088511:web:56cd585994d28f5f6670ca',
    messagingSenderId: '532773088511',
    projectId: 'kisisel-asistan-381e6',
    authDomain: 'kisisel-asistan-381e6.firebaseapp.com',
    storageBucket: 'kisisel-asistan-381e6.firebasestorage.app',
    measurementId: 'G-Z7Y6N0RC09',
  );
}
